### ISSUE TITLE
compute_jackson_cheby_coeff IndexError

### ISSUE THREAD

**Issue by scottgigante** [epfl-lts2/pygsp#39]
compute_jackson_cheby_coeff is indexing with a float. PR coming.
```
>>> import pygsp
>>> G = pygsp.graphs.Minnesota()
>>> G.estimate_lmax()
>>> pygsp.filters.compute_jackson_cheby_coeff([0, G.lmax/2], [0, G.lmax], 30)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scottgigante/.local/lib/python3.7/site-packages/pygsp/filters/approximations.py", line 209, in compute_jackson_cheby_coeff
    (np.sin(i * np.arccos(filter_bounds[0])) - np.sin(i * np.arccos(filter_bounds[1])))
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by mdeff** [comment]
Thanks!
